#!/bin/bash

#source <(kubectl completion bash)

complete -C aws_completer aws

if [ -f $(/opt/homebrew/bin/brew --prefix)/etc/bash_completion ]; then
  . $(/opt/homebrew/bin/brew --prefix)/etc/bash_completion
fi
