#!/bin/bash

# Terminal Colors
export CLICOLOR=1
export LSCOLORS=ExFxBxDxCxegedabagacad

# Preserve bash history in multiple terminal windows
export HISTCONTROL=ignoredups:erasedups  # no duplicate entries
export HISTSIZE=100000                   # big big history
export HISTFILESIZE=100000               # big big history
export HISTTIMEFORMAT="%h %d %H:%M:%S> "

# Save and reload the history after each command finishes
export PROMPT_COMMAND="history -a; history -c; history -r; $PROMPT_COMMAND"

# Java + Friends
#export JAVA_VERSION=11
#export JAVA_VERSION=1.8
#export JAVA_HOME=$(/usr/libexec/java_home -v $JAVA_VERSION)
export JAVA_HOME="${HOME}/.sdkman/candidates/java/current"
export ANT_OPTS="-Xmx512m -XX:MaxPermSize=256m"
export MAVEN_OPTS="-Xmx756m"

# Python
export PATH=/Users/gbunney/Library/Python/3.8/bin:$PATH

# SSH
export SSH_INSECURE='-o StrictHostKeyChecking=no'

# Go
export GOPATH=$HOME/dev/golang
export GOROOT=/usr/local/opt/go/libexec
export GOBIN=$GOPATH/bin
export PATH=$PATH:$GOPATH
export PATH=$PATH:$GOPATH/bin
export PATH=$PATH:$GOROOT/bin

# Terraform
export TF_PLUGIN_CACHE_DIR=$HOME/.terraform.d/plugin-cache

# SDKMan
export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"

# Krew
export PATH=$PATH:$HOME/.krew/bin

## Direnv
#eval "$(direnv hook bash)"
#export DIRENV_WARN_TIMEOUT=10s

## GPG
export GPG_TTY=$(tty)

# GCP
source "/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/path.bash.inc"
source "/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.bash.inc"

# Spinnaker
if [ -f $HOME/.spinnaker-env.sh ]; then
  source $HOME/.spinnaker-env.sh
fi

export NVM_DIR="$HOME/.nvm"
[ -s "/usr/local/opt/nvm/nvm.sh" ] && . "/usr/local/opt/nvm/nvm.sh"  # This loads nvm
[ -s "/usr/local/opt/nvm/etc/bash_completion.d/nvm" ] && . "/usr/local/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion
